import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: "#faf5ff", //purple theme
    // backgroundColor: "#f7d6d0",
    // backgroundColor: "#e3d6c6",
    backgroundColor: "#f9f4f0",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  // title2: {
  //   // color: "#4a148c",
  //   color: "#c785a5",
  //   fontSize: 28,
  //   fontWeight: "bold",
  //   textAlign: "center",
  //   textShadowColor: "#d1c4e9",
  //   textShadowOffset: { width: 2, height: 2 },
  //   textShadowRadius: 5,
  // },
  // title3: {
  //   fontSize: 28,
  //   fontWeight: "bold",
  //   color: "#ffffff",
  //   textAlign: "center",
  //   textShadowColor: "rgba(0, 0, 0, 0.7)",
  //   textShadowOffset: { width: 2, height: 2 },
  //   textShadowRadius: 5,
  // },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#5a4a42",
    textAlign: "center",
  },
  petContainer: {
    flex: 1,
    paddingTop: 20,
    alignItems: "center",
  },
  petModel: {
    width: Dimensions.get("window").width * 0.8,
    height: Dimensions.get("window").height * 0.4,
    backgroundColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  petBox: {
    width: 200,
    height: 200,
    borderRadius: 20,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    marginBottom: 20,
  },
  // section1: {
  //   backgroundColor: "#fff",
  //   padding: 15,
  //   borderRadius: 10,
  //   // marginBottom: 15,
  //   marginVertical: 15,
  //   shadowColor: "#000",
  //   shadowOffset: { width: 0, height: 2 },
  //   shadowOpacity: 0.1,
  //   shadowRadius: 4,
  //   elevation: 3,
  //   width: "96%",
  // },

  speechBubble: {
    position: "absolute",
    top: 10,
    backgroundColor: "white",
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 2, height: 2 },
  },
  message: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#5a4a42",
  },
  buttonsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    paddingBottom: 20,
  },
  interactionButtonsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    paddingBottom: 20,
    marginHorizontal: 20,
    width: 400,
  },
  recoveryTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  section: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
    // marginHorizontal: 40,
    // shadowColor: "#000",
    // shadowOffset: { width: 0, height: 2 },
    // shadowOpacity: 0.1,
    // shadowRadius: 4,
    // elevation: 3,
    width: "95%",
  },
  healthContainer: {
    flexDirection: "row",
    alignItems: "center",
    // justifyContent: "space-around",
    justifyContent: "space-between",
    // width: "90%",
    // paddingHorizontal: 15,
    // marginVertical: 30,
  }, //
  healthText: {
    fontSize: 18,
    fontWeight: "bold",
    // color: "#d81b60",
    // color: "#7b1fa2",
    // color: "#5a2a2a",
    // color: "#3d3d3d",
    color: "#5a4a42",
    marginEnd: 5,
  },
  progressText: {
    // color: "#4a148c", //purple
    color: "#3d3d3d",
    // color: "#5a4a42",
    position: "absolute",
    alignSelf: "center",
    fontWeight: "bold",
    top: 2,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    margin: 10,
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 2, height: 2 },
  },
  interactionButtonWrapper: {
    alignItems: "center",
    // marginHorizontal: 5,
    // marginHorizontal: 20,
    // marginBottom: 30,
    // width: "40%",
  },
  interactionText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#5a4a42",
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  buttonEnabled: {
    //backgroundColor: "#ba68c8"
    backgroundColor: "#ff6b6b",
  },
  buttonDisabled: {
    // backgroundColor: "#d1a3e0",
    backgroundColor: "#ffb3b3",
    opacity: 0.6,
  },
  // hatchCountdownText2: {
  //   fontSize: 18,
  //   fontWeight: "bold",
  //   color: "#7b1fa2",
  //   backgroundColor: "#f3e5f5",
  //   paddingVertical: 8,
  //   paddingHorizontal: 15,
  //   borderRadius: 15,
  //   borderWidth: 2,
  //   borderColor: "#ce93d8",
  //   textAlign: "center",
  //   marginTop: 10,
  //   shadowColor: "#000",
  //   shadowOpacity: 0.2,
  //   shadowOffset: { width: 2, height: 2 },
  // },
  hatchCountdownText: {
    fontSize: 38,
    fontWeight: "bold",
    color: "#ff6b6b",
    // backgroundColor: "#ffd6d6",
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: "#ff6b6b",
    textAlign: "center",
    marginTop: 20,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 2, height: 2 },
  },
  hatchButton: {
    // backgroundColor: "#ffd6d6",
    backgroundColor: "#ff6b6b",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#ff6b6b",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 2, height: 2 },
    marginVertical: 20,
  },
  hatchButtonText: {
    fontSize: 20,
    fontWeight: "bold",
    // color: "#ff6b6b",
    color: "white",
    // textShadowColor: "white",
    // textShadowOffset: { width: 1, height: 1 },
    // textShadowRadius: 5,
  },
  // hatchButton2: {
  //   backgroundColor: "#f8bbd0",
  //   paddingVertical: 15,
  //   paddingHorizontal: 30,
  //   borderRadius: 20,
  //   borderWidth: 2,
  //   borderColor: "#e91e63",
  //   shadowColor: "#000",
  //   shadowOpacity: 0.3,
  //   shadowOffset: { width: 2, height: 2 },
  //   marginTop: 20,
  // },
  // hatchButtonText2: {
  //   fontSize: 20,
  //   fontWeight: "bold",
  //   color: "#880e4f",
  //   textShadowColor: "white",
  //   textShadowOffset: { width: 1, height: 1 },
  //   textShadowRadius: 5,
  // },
});
